### PR TITLE
Added deadzone to analog stick

### PR DESCRIPTION
**Pull request by Limon93**
Added a small deadzone for analog readings. Solved phantom movement on my controller.
The implementation is a little brutal.

### CODE REVIEW

**Comment by JPZV** [comment]
Nice done!!!

I have some tips:

1) We should check each axis independently. i.e. `if -10 ≤ x ≤ 10 then x = 0` and `if -10 ≤ y ≤ 10 then y = 0` because of the edge case about having an analog stick with drifting on a single axis.
2) We can simplify the `if (x >= -10 && x <= 10)` with just `if (abs(x) <= 10)`, making it easiest to read ;)

But in general you did great!!! If you can make those little changes, I'd merge asap :)

**Comment by Limon93** [comment]
Hi JPZV, i modified the code using both tips you gave me :)

**Review by JPZV — APPROVED** [review]

**Comment by JPZV** [comment]
Well done!!!

Soon it'll be released as a new version with your changes. Thanks for your support! ;)

**Comment by Limon93** [comment]
Thanks for your work JPZV :)

**Pull request merged**
